---
# for local docker compose
receivers:
  otlp:
    protocols:
      http:
      grpc:
        include_metadata: 'true'
  hostmetrics:
    collection_interval: '10s'
    scrapers:
      cpu:
      memory:
      load:
      network:
processors:
  batch:
    timeout: '1s'
  memory_limiter:
    check_interval: '1s'
    limit_mib: '500'
    spike_limit_mib: '200'
    limit_percentage: '85'
  resourcedetection:
    detectors: ['system', 'env', 'gcp', 'docker']
    override: 'true'
  resource/framework:
    attributes:
      - key: 'deployment.environment'
        value: 'dev'
        action: 'upsert'
      - key: 'ingka.legal_company'
        value: 'ingka'
        action: 'upsert'
      - key: 'ingka.system_name'
        value: 'ob'
        action: 'upsert'
      - key: 'ingka.team'
        value: 'outbound'
        action: 'upsert'
      - key: 'ingka.version'
        value: '0.4.1'
        action: 'upsert'
exporters:
  prometheus:
    endpoint: '0.0.0.0:8889'
  loki:
    endpoint: 'http://loki:3100/loki/api/v1/push'
    tls:
      insecure: 'true'
    default_labels_enabled:
      exporter: 'true'
      job: 'true'
  otlp/tempo:
    endpoint: 'tempo:4317'
    tls:
      insecure: 'true'
service:
  pipelines:
    metrics:
      receivers: ['otlp', 'hostmetrics']
      processors: ['memory_limiter', 'batch', 'resource/framework']
      exporters: ['prometheus']
    traces:
      receivers: ['otlp']
      processors: ['memory_limiter', 'batch', 'resource/framework']
      exporters: ['otlp/tempo']
    logs:
      receivers: ['otlp']
      processors: ['memory_limiter', 'batch', 'resource/framework']
      exporters: ['loki']
