name: PR label and comment

on:
  pull_request:
    types: [ opened ]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Add label to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
          -d '{"labels":["run-fast"]}'

      - uses: mshick/add-pr-comment@v2
      
        with:
          message: |
            ### 🎉 Thank you for your Pull Request!
            
            #### Please ensure that:
            - [ ] You have ran the tests locally before your commits !! This will help to avoid surprises later along the road..

            #### :radio_button: Add following label to your PR to make changes in the tests execution.
                  Check right side of this PR screen to find `Labels` section:

            - Label: `run-fast`: Runs only the build, no tests! This is added as default. You can change this behaviour by adding more labels mentioned below.
            - Label: `run-tests`: Run Tests too. You may only need to add this when you really want it. Ideally when you are ready to merge.

            Obviously, `run-tests` and `run-fast` are mutually exclusive. You can only have one of them at a time. This will be taken care automatically.

            **NOTE** that you cannot merge PRs without running all your tests with the last committed changes!

            ---
              
            _Happy Coding!_