name: PR label and comment

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Add label to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
          -d '{"labels":["your-label"]}'

      # - name: add label
      #   uses: actions-ecosystem/action-add-labels@v1
      #   # if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
      #   with:
      #     labels: run-fast

      - uses: mshick/add-pr-comment@v2
      
        with:
          message: |
            ### 🎉 Thank you for your Pull Request!

            #### :radio_button: Add the following label to your PR to make changes in the build workflow execution:

            - `run-fast`: Runs only the build, no tests. This is default. You can change this behaviour by adding the labels mentioned below.
            - `run-tests`: Run Tests. You only need to add this when it is really ready to merge, preferably after PR reviews and all.

            **Please ensure that:**
            - [ ] You have ran the tests locally, always.
                  This will help avoid surprises when you add the label `run-tests` and notice test failures.

            ---
              
            _Happy Coding!_