name: PR label and comment

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Add label to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels \
          -d '{"labels":["your-label"]}'

      # - name: add label
      #   uses: actions-ecosystem/action-add-labels@v1
      #   # if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
      #   with:
      #     labels: run-fast

      - uses: mshick/add-pr-comment@v2
      
        with:
          message: |
            ### 🎉 Thank you for your Pull Request!
            
            **Please ensure that:**
            - [ ] You have ran the tests locally before your commits!
                  This will help to avoid surprises later along the road.

            #### :radio_button: Add following label to your PR to make changes in the tests execution:

            - `run-fast`: Runs only the build, no tests! This is added as default. You can change this behaviour by adding more labels mentioned below.
            - `run-tests`: Run Tests. You only need to add this when you want it, ideally right before merge, preferably after PR reviews and all.


            **NOTE** that you cannot merge the PR without running the tests with the last committed changes!
            
            ---
              
            _Happy Coding!_