name: PR Conditional Workflow

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  conditional-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Analysis if Label Exists
        if: contains(github.event.pull_request.labels.*.name, 'run-tests')
        run: echo "Label 'run-tests' is present, hence going to run all tests..."
        
      - name: Default Step
        run: echo "This runs regardless of any labels"
