name: Remove PR Label

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  remove-label:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check if Label Exists
        id: check-label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            core.setOutput('labelExists', labels.includes('run-tests'));

      - name: Remove Label
        if: steps.check-label.outputs.labelExists == 'true'
        run: |
          # Use GitHub API to remove the label
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/run-fast
