name: Slack Send

on:
  push:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.27.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     channel-id: 'cps-gke-alerts-test'
      #     # For posting a rich message using Block Kit
      #     payload: |
      #       {
      #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "attachments": [
                {
                  "fallback": "New CPS Release published",
                  "color": "#36a64f",
                  "pretext": "New release published by ingka-cps-ci",
                  "title": "<https://github.com/ingka-group-digital/cps-catalogue/releases/tag/242|Release - CPS-v242>",
                  "text": "\n\n\nReleased components:\n• cps-pack-backend v2.34.0\n• cps-pick-backend v0.92.0",
                  "fields": [
                    {
                      "title": "\n\n\nDeployment log",
                      "value": "<https://github.com/ingka-group-digital/cps-catalogue|ingka-group-digital/cps-catalogue> | Today at 10:51 AM",
                      "short": false
                    }
                  ],
                  "footer": "GitHub Repository",
                  "footer_icon": "https://github.githubassets.com/favicon.ico"
                }
              ]
            }


        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK