name: Slack Send

on:
  push:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.27.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     channel-id: 'cps-gke-alerts-test'
      #     # For posting a rich message using Block Kit
      #     payload: |
      #       {
      #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "attachments": [
                {
                  "fallback": "GitHub Repository Release",
                  "color": "#24292e",
                  "pretext": "New GitHub Repository Release Information",
                  "author_name": "GitHub",
                  "author_link": "https://github.com",
                  "author_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                  "title": "New Release: v1.2.0",
                  "title_link": "https://github.com/username/repository/releases/tag/v1.2.0",
                  "text": "A new release `v1.2.0` has been published for the repository *repository-name*.",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "username/repository",
                      "short": true
                    },
                    {
                      "title": "Tag",
                      "value": "v1.2.0",
                      "short": true
                    },
                    {
                      "title": "Published By",
                      "value": "John Doe",
                      "short": true
                    },
                    {
                      "title": "Release Date",
                      "value": "September 5th, 2024",
                      "short": true
                    },
                    {
                      "title": "Changelog",
                      "value": "- Added feature A\n- Improved performance of B\n- Fixed bug in C",
                      "short": false
                    },
                    {
                      "title": "Assets",
                      "value": "[Source Code (zip)](https://github.com/username/repository/archive/refs/tags/v1.2.0.zip)\n[Source Code (tar.gz)](https://github.com/username/repository/archive/refs/tags/v1.2.0.tar.gz)\n[Binary Release](https://github.com/username/repository/releases/download/v1.2.0/binary-release.tar.gz)",
                      "short": false
                    }
                  ],
                  "thumb_url": "https://github.githubassets.com/images/modules/logos_page/Octocat.png",
                  "footer": "GitHub Repository",
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "ts": 1633728000
                }
              ]
            }


        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK