name: Slack Send

on:
  push:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      # - name: Post to a Slack channel
      #   id: slack
      #   uses: slackapi/slack-github-action@v1.27.0
      #   with:
      #     # Slack channel id, channel name, or user id to post message.
      #     # See also: https://api.slack.com/methods/chat.postMessage#channels
      #     channel-id: 'cps-gke-alerts-test'
      #     # For posting a rich message using Block Kit
      #     payload: |
      #       {
      #         "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
      #             }
      #           }
      #         ]
      #       }
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "New Order Received :package:",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Order Summary",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Order ID:* 12345678\n*Customer Name:* John Doe\n*Total:* $199.99\n*Order Date:* September 4th, 2024"
                  },
                  "accessory": {
                    "type": "image",
                    "image_url": "https://example.com/order-image.png",
                    "alt_text": "Order Image"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Order Details:*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Item:* iPhone 14 Pro"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Price:* $999.99"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Item:* AirPods Pro"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Price:* $199.99"
                    }
                  ]
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Order will be shipped to *123 Apple Street, Cupertino, CA*."
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Order",
                        "emoji": true
                      },
                      "url": "https://example.com/orders/12345678",
                      "style": "primary"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Contact Support",
                        "emoji": true
                      },
                      "url": "https://example.com/support",
                      "style": "danger"
                    }
                  ]
                }
              ],
              "attachments": [
                {
                  "fallback": "Order Update",
                  "color": "#36a64f",
                  "pretext": "Shipping Information",
                  "author_name": "Shipping Department",
                  "author_link": "https://example.com/shipping",
                  "author_icon": "https://example.com/shipping-icon.png",
                  "title": "Order Shipped",
                  "text": "Your order has been shipped and is on its way.",
                  "fields": [
                    {
                      "title": "Carrier",
                      "value": "FedEx",
                      "short": true
                    },
                    {
                      "title": "Tracking Number",
                      "value": "1Z9999999999999999",
                      "short": true
                    }
                  ],
                  "image_url": "https://example.com/shipping-status.png",
                  "thumb_url": "https://example.com/shipping-icon.png",
                  "footer": "Company Name",
                  "footer_icon": "https://example.com/footer-icon.png",
                  "ts": 1633728000
                }
              ]
            }


        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK